### ISSUE TITLE
shortage of AudioTrack on Android

### ISSUE THREAD

**Issue by pankona** [hajimehoshi/oto#27] opened 2017-08-17 03:47 UTC
Hi @hajimehoshi !

On android, I faced problem to playback audio.
Audio playback does work at launching application, but some times after, audio playback doesn't work at all. I investigated and found that this problem seems to be caused by shortage of AudioTrack.

Around this part, AudioTrack is allocated and it is registered to GlobalRef in JNI.
https://github.com/hajimehoshi/oto/blob/8ab1cc50f21ad05f93bf99dc8c44d6aa101c29c9/player_android.go#L104-L113

I think AudioTracks should be released after their use, and also be deleted from GlobalRef.
It seems there's number limitation for allocatiing AudioTracks, they can be available in same time on Android (about 30?, sorry I couldn't find out specification.).

So my application playbacks audio again and again and again for sound effects, I noticed such issue.
I found this problem with application that is generated by `gomobile build`.

(If you don't mind, I will create a pull request and I'd like you to check my modification to fix this problem.)

**Comment by hajimehoshi** [comment] 2017-08-17 04:33
CC @wasedaigo just in case

**Comment by hajimehoshi** [comment] 2017-08-17 04:34
Thank you for your reporting, I'll take a look later

> (If you don't mind, I will create a pull request and I'd like you to check my modification to fix this problem.)

Sure, that would be helpful!

**Comment by hajimehoshi** [comment] 2017-08-17 11:04
I think the AudioTrack is created only once. I don't see what is the problem...

**Comment by hajimehoshi** [comment] 2017-08-17 11:08
> So my application playbacks audio again and again and again for sound effects, I noticed such issue.

Ah, you created the player and close it, and repeat it again and again? OK so the problem is that `Close` doesn't dispose the AudioTrack. Is my understanding correct?

**Comment by pankona** [comment] 2017-08-17 11:22
Thank you for your comments!
Yes, you are exactlly right! I guess it is necessay to call release for AudioTrack and delete it from GlobalRef at Close().
Thank you so much taking care of this issue. I'll submit PR later.

**Closed** 2017-08-18 11:04 UTC
Labels: bug
