### ISSUE TITLE
undefined newDriver

### ISSUE THREAD

**Issue by triole** [hajimehoshi/oto#118] opened 2020-08-06 11:34 UTC
Hi, I tried to make static builds of the module. What can see below what I got. First line of the blocks is the command I used. Below the output.

Actually I stumbled across this because I was trying to make static builds of https://github.com/sentriz/gonic.git. Do you have any ideas?

```
GOARM=6 GOARCH=arm CGO_ENABLED=0 go build -a -o "build/armv6l/oto" .
# github.com/hajimehoshi/oto
./context.go:69:12: undefined: newDriver

GOARM=7 GOARCH=arm CGO_ENABLED=0 go build -a -o "build/armv7l/oto" .
# github.com/hajimehoshi/oto
./context.go:69:12: undefined: newDriver

GOARCH=arm64 CGO_ENABLED=0 go build -a -o "build/armv8l/oto" .
# github.com/hajimehoshi/oto
./context.go:69:12: undefined: newDriver

GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -o "build/x86_64/oto" .
# github.com/hajimehoshi/oto
./context.go:69:12: undefined: newDriver
```

Thanks for your effort and this brilliant library.

Cheers.

**Comment by hajimehoshi** [comment] 2020-08-06 11:44
Hi,

> CGO_ENABLED=0

This is the cause. Oto requires Cgo.

**Comment by triole** [comment] 2020-08-06 11:54
Hi again, thank you for your quick response. As I understood the issue static builds unfortunately require `CGO_ENABLED=0`. I must have missed that `oto` requires CGO. No static builds for me as it seems.

**Comment by hajimehoshi** [comment] 2020-08-06 12:29
Note that you need to specify CGO_ENABLED=1 explicitly if you do cross-compiling.

**Comment by Noofbiz** [comment] 2020-08-06 13:06
According to [this](https://github.com/shadowmint/go-static-linking) you can link a static library using gcc to build the C library to a .a file, then you can link to the .a file using CGo. So you can grab the openAL Soft static library from [here](https://kcat.strangesoft.net/openal.html), build it with gcc and point oto to the .a file. 
Good luck!

**Comment by hajimehoshi** [comment] 2021-08-21 17:21
Let me close this. Feel free to reopen if you still have a question.

**Closed** 2021-08-21 17:20 UTC
