### ISSUE TITLE
Write uses 100% CPU when blocking

### ISSUE THREAD

**Issue by faiface** [hajimehoshi/oto#10] opened 2017-06-18 17:40 UTC
I was just testing out the example in [go-mp3](https://github.com/hajimehoshi/go-mp3/tree/master/example) and the program is utilizing full 100% of CPU (well, 25% on a 4 core CPU). This is cause by the `Write` method's busy loop.

**Comment by hajimehoshi** [comment] 2017-06-18 17:43
Thank you for reporting. I'll take a look

**Comment by hajimehoshi** [comment] 2017-06-18 17:46
Additionally, doesn't this consume much memory like 500MB? Hmm...

**Comment by hajimehoshi** [comment] 2017-06-18 17:49
I think it's fixed (15%-20% on my MacBook Pro)

**Comment by faiface** [comment] 2017-06-18 17:50
Btw, that fix is sort of not correct, it's wrong with different buffer sizes.

**Comment by hajimehoshi** [comment] 2017-06-18 17:51
Ah that's true. Do you have any suggestion?

**Comment by faiface** [comment] 2017-06-18 17:54
If there's a way to implement this blocking fully correctly through audio playback backends (OpenAL, Windows API, and so on), I'd implement it directly in the implementations. If not, then wait some time based on the player's buffer size.

**Comment by hajimehoshi** [comment] 2017-06-18 18:21
I prefer the latter. I'd like to avoid platform-dependent code if possible.

**Comment by hajimehoshi** [comment] 2017-06-19 01:08
* `time.Sleep` is called only when blocking (= `n` is 0)
* Sleeping time is calculated based on the buffer size. The sleeping time is a quoter of the time spent by the player consuming the buffer size. 'Quoter' (1/4) is an arbitrary ratio.

@faiface, does this make sense?

**Comment by faiface** [comment] 2017-06-19 14:03
Makes sense and fixes the issue. Is the write method in the implementation guaranteed to always return `n = 0` if the buffer is full? So, does it always return either `len(data)` or `0`?

**Comment by faiface** [comment] 2017-06-19 14:19
The remaining CPU time comes from the MP3 decoding, so that's alright.

**Comment by hajimehoshi** [comment] 2017-06-19 14:30
> Makes sense and fixes the issue. Is the write method in the implementation guaranteed to always return n = 0 if the buffer is full? So, does it always return either len(data) or 0?

For the current implementation, yes. So the inner player's Write would not be `io.Writer`. We'd need to compromise, for example, renaming Write to something different.

`len(data)` is not 0 in this case since if `len(data)` is 0, the for-loop condition is always false.

**Comment by hajimehoshi** [comment] 2017-06-19 14:34
> So, does it always return either len(data) or 0?

Ah sorry, I misread that. The returned value would be in between 0 and `len(data)`. In the current implementation, player's Write tries to write as much as possible, and returns soon. If the returned value is 0, no buffer is available.

**Comment by hajimehoshi** [comment] 2017-06-19 14:50
As @faiface and I discussed, I was misunderstanding the condition when the buffer is full. When not all the data is written, the buffer should be full. Fixed.

**Comment by alistanis** [comment] 2017-06-22 05:50
@hajimehoshi @faiface Hey guys, through some testing this fix introduces artifacts in playback for me. When I multiplied it by Milliseconds instead of Seconds it reduced single core CPU usage from ~99 to ~14% and removed artifacts for me - I can record an example for you if you'd like.

**Comment by alistanis** [comment] 2017-06-22 06:01
The sweet spot may be 50 * Millisecond (we need to test that on different core frequencies though, mine is 2.6 Ghz) - that's when I couldn't hear a discernible difference, playback was smooth, and I was maxed out at ~6% single core CPU usage.

**Comment by hajimehoshi** [comment] 2017-06-22 07:10
Thanks, but could you tell me which OS did you experiment this?

**Comment by hajimehoshi** [comment] 2017-12-28 10:46
Let me close this. Let' revisit when the problem is found again.

**Closed by hajimehoshi** 2017-12-28 10:46 UTC
Labels: bug
